### ISSUE TITLE
Вывести значение альткоина в баксах

### ISSUE THREAD

**Issue by kirush0280** [rasskazovaleksey/criptobot#10]
Имеем:
BTC / USDT - Покупка - объем 3.72 BTC - цена 9374.9
LSK / BTC - Покукпка -объем 7.4 BTC - цена 0.00303996 (~$ {9374.9*0.00303996})

во всех парах кроме "BTC/USDT", хотят в скобках видеть приблизительное значение в баксах (смысл в скобках расписан). Стоимость доработки предварительно согласуй со мной :)

**Comment by rasskazovaleksey** [comment]
[ADDED] in ce0f988
