### ISSUE TITLE
 округлить значение "цена" в паре BTC/USDT

### ISSUE THREAD

**Issue by kirush0280** [rasskazovaleksey/criptobot#9]
Алексей, добавь плз новый if только для этой пары:
сейчас видим:
BTC / USDT - Покупка - объем 3.72 BTC - цена 9374.900000 USDT
а хотят:
BTC / USDT - Покупка - объем 3.72 BTC - цена 9374 USDT (или 9375 не принципиально)

**Comment by rasskazovaleksey** [comment]
[ADDED] in ce0f988
